const $=s=>document.querySelector(s);let config={models:[]},game=null,mode='human-ai',wallMode=null,pawnSelected=false,busy=false,lastSetup=null;
const api=async(path,opts={})=>{const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j};
const fmt=n=>n==null?'—':Number(n).toLocaleString();
function agentEditor(root,player){root.innerHTML=`<legend>Player ${player}</legend><div class="field"><label>Controller</label><select class="kind"><option value="classical">Classical solver</option>${config.models.map(m=>`<option value="model:${m.name}">${m.name}</option>`).join('')}</select></div><div class="classical"><div class="field"><label>Time per move</label><input class="time" type="number" value="0.5" min="0" max="600" step="0.1"></div><div class="field"><label>Maximum depth</label><input class="depth" type="number" value="4" min="1" max="8"></div></div><div class="model-note"></div>`;const sel=root.querySelector('.kind');const sync=()=>{const model=sel.value.startsWith('model:');root.querySelector('.classical').hidden=model;const name=sel.value.slice(6),m=config.models.find(x=>x.name===name);root.querySelector('.model-note').textContent=m?`${m.architecture.toUpperCase()}${m.elo!=null?' · Elo '+m.elo:''}${m.positions?' · '+fmt(m.positions)+' positions':''}${m.dataset?' · '+m.dataset:''}${m.loaded?' · preloaded':''}`:'Iterative deepening with a persistent move cache.'};sel.onchange=sync;sync()}
function spec(root){const v=root.querySelector('.kind').value;if(v.startsWith('model:'))return{kind:'model',checkpoint:v.slice(6)};return{kind:'classical',timeLimit:+root.querySelector('.time').value,depth:+root.querySelector('.depth').value}}
function syncMode(){document.querySelectorAll('.segmented button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#humanOptions').hidden=mode!=='human-ai';$('#p1Setup').hidden=mode==='human-ai'&&$('#humanSide').value==='1';$('#p2Setup').hidden=mode==='human-ai'&&$('#humanSide').value==='2'}
async function launch(body){lastSetup=body;game=await api('/api/games',{method:'POST',body:JSON.stringify(body)});wallMode=null;pawnSelected=false;render();autoMove()}
async function start(){const body={mode,p1Col:Math.floor(Math.random()*9),p2Col:Math.floor(Math.random()*9)};if(mode==='ai-ai'){body.p1=spec($('#p1Setup'));body.p2=spec($('#p2Setup'))}else{body.humanSide=$('#humanSide').value;body.ai=spec(body.humanSide==='1'?$('#p2Setup'):$('#p1Setup'))}await launch(body);$('#setup').close()}
async function rematch(){if(!lastSetup)return;await launch({...lastSetup,p1Col:Math.floor(Math.random()*9),p2Col:Math.floor(Math.random()*9)})}
function humanTurn(){return game&&!game.gameOver&&game.players[String(game.turn)].kind==='human'}
function pawnPos(p){const [r,c]=game.pawns[p];return{left:(c+.5)/9*100,top:(r+.5)/11*100}}
function moveKey(m){return`${m.kind}:${m.at.join(',')}`}
async function play(move){if(busy)return;busy=true;try{game=await api(`/api/games/${game.id}/move`,{method:'POST',body:JSON.stringify(move)});wallMode=null;pawnSelected=false;render()}catch(e){showStatus(e.message,true)}finally{busy=false}await autoMove()}
async function autoMove(){if(!game||game.gameOver||humanTurn()||busy)return;busy=true;const label=agentLabel(game.players[String(game.turn)]);const started=performance.now();const tick=()=>showStatus(`${label} is thinking… ${((performance.now()-started)/1000).toFixed(1)}s`);tick();const timer=setInterval(tick,100);try{game=await api(`/api/games/${game.id}/ai-move`,{method:'POST',body:'{}'});render()}catch(e){showStatus(e.message,true)}finally{clearInterval(timer);busy=false}if(game&&!game.gameOver&&!humanTurn())setTimeout(autoMove,260)}
function agentLabel(a){return a.kind==='human'?'Human':a.kind==='model'?a.checkpoint:`Classical · ${a.timeLimit}s`}
function showStatus(text,error=false){$('#status').textContent=text;$('#status').style.color=error?'#ef7f78':''}
function renderPlayer(p){const a=game.players[String(p)],panel=$(`#p${p}Panel`);panel.classList.toggle('active',game.turn===p&&!game.gameOver);const left=game.wallsLeft[String(p)];panel.innerHTML=`<span class="eyebrow">PLAYER ${p}</span><h3>${a.kind==='human'?'Human':a.kind==='model'?'Neural model':'Classical AI'}</h3><div class="agent-name" title="${agentLabel(a)}">${agentLabel(a)}</div><div class="wall-rack">${Array.from({length:9},(_,i)=>`<button class="rack-wall ${i>=left?'used':''}" ${a.kind!=='human'||i>=left?'disabled':''} aria-label="Pick up wall"></button>`).join('')}</div><div class="agent-name" style="margin-top:9px">${left} walls remaining</div>`;panel.querySelectorAll('.rack-wall:not(.used)').forEach(b=>b.onclick=()=>{if(humanTurn()&&game.turn===p){wallMode=wallMode||'H';pawnSelected=false;render()}})}
function render(){if(!game)return;renderPlayer(1);renderPlayer(2);const board=$('#board');board.innerHTML='';const legalMoves=new Set(game.legal.filter(m=>m.kind==='m').map(moveKey));for(let r=0;r<11;r++)for(let c=0;c<9;c++){const b=document.createElement('button');b.className='cell'+((r===0||r===10)?' endzone':'');if(Object.values(game.goals).some(g=>g[0]===r&&g[1]===c))b.classList.add('goal');const key=`m:${r},${c}`;if(humanTurn()&&pawnSelected&&legalMoves.has(key)){b.classList.add('legal');b.onclick=()=>play({kind:'m',at:[r,c]})}b.ondragover=e=>{if(humanTurn()&&legalMoves.has(key))e.preventDefault()};b.ondrop=e=>{e.preventDefault();if(humanTurn()&&legalMoves.has(key))play({kind:'m',at:[r,c]})};board.appendChild(b)}
  for(const p of ['1','2']){const pos=pawnPos(p),el=document.createElement('div');el.className=`pawn p${p}`+(pawnSelected&&+p===game.turn?' selected':'');el.style.left=pos.left+'%';el.style.top=pos.top+'%';el.draggable=humanTurn()&&+p===game.turn;el.onclick=()=>{if(humanTurn()&&+p===game.turn){pawnSelected=!pawnSelected;wallMode=null;render()}};el.ondragstart=()=>{pawnSelected=true};board.appendChild(el)}
  for(const [r,c,o] of game.walls){const w=document.createElement('div');w.className=`wall ${o.toLowerCase()}`;if(o==='H'){w.style.left=(c+1)/9*100+'%';w.style.top=(r+1)/11*100+'%'}else{w.style.left=(c+1)/9*100+'%';w.style.top=(r+1)/11*100+'%'}board.appendChild(w)}
  if(wallMode&&humanTurn()){const legal=new Set(game.legal.filter(m=>m.kind==='w').map(moveKey));for(let r=1;r<=8;r++)for(let c=0;c<=7;c++){const key=`w:${r},${c},${wallMode}`;const slot=document.createElement('button');slot.className=`wall-slot ${wallMode.toLowerCase()}`;slot.style.left=(c+1)/9*100+'%';slot.style.top=(r+1)/11*100+'%';slot.disabled=!legal.has(key);if(legal.has(key))slot.onclick=()=>play({kind:'w',at:[r,c,wallMode]});board.appendChild(slot)}}
  $('#playAgain').hidden=!game.gameOver;
  if(game.winner)showStatus(`Player ${game.winner} wins`);else if(game.drawReason)showStatus(`Draw · ${game.drawReason}`);else if(humanTurn())showStatus(wallMode?`Place a ${wallMode==='H'?'horizontal':'vertical'} wall`:`Player ${game.turn} · your move`);else showStatus(`${agentLabel(game.players[String(game.turn)])} to move`);
  $('#history').innerHTML=game.history.map(h=>`<li>P${h.player} · ${h.kind==='m'?String.fromCharCode(65+h.at[1])+h.at[0]:String.fromCharCode(65+h.at[1])+h.at[0]+h.at[2]}</li>`).join('');const li=game.lastInfo;$('#telemetry').textContent=li?`${li.solver} · ${(li.elapsed*1000).toFixed(0)} ms`:'No moves yet'}
document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'&&wallMode){wallMode=wallMode==='H'?'V':'H';render()}if(e.key==='Escape'&&(wallMode||pawnSelected)){wallMode=null;pawnSelected=false;render()}});
document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;syncMode()});$('#humanSide').onchange=syncMode;$('#setupForm').onsubmit=e=>{e.preventDefault();start()};$('#newGame').onclick=()=>$('#setup').showModal();$('#playAgain').onclick=()=>rematch();
(async()=>{config=await api('/api/config');agentEditor($('#p1Setup'),1);agentEditor($('#p2Setup'),2);syncMode();$('#setup').showModal()})().catch(e=>showStatus(e.message,true));
